version: '3.8'
services:
  web:
    image: landing-percapita-web
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./vite.config.ts:/app/vite.config.ts
      - ./index.html:/app/index.html   